--- #YAML:1.0
name: Math-Series
version: 1.01
abstract: Perl extension dealing with mathematic series
license: perl
distribution_type: module
requires:
  Math::Sequence: 1.00
  Test::More: 0.44
  Math::Symbolic: 0.128
  Parse::RecDescent: 1.8
dynamic_config: 0

